apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: postgres-master
spec:
  selector:
    matchLabels:
      app: postgres
      role: master
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        role: master
    spec:
      containers:
        - name: master
          image: postgres:9.6
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: postgres-master-db


