apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: pybossa-workers
spec:
  selector:
    matchLabels:
      app: pybossa
      role: worker
  replicas: 1
  template:
    metadata:
      labels:
        app: pybossa
        role: worker
    spec:
      containers:
        - name: pybossa-worker
          image: pybossa:2.7.2
          command:
            - python
            - app_context_rqworker.py
            - scheduled_jobs
            - super
            - high
            - medium
            - low
            - email
            - maintenance
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: uploads
              mountPath: /opt/pybossa/uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: pybossa-uploads

