apiVersion: v1
kind: Service
metadata:
  name: postgres-master
  labels:
    app: postgres
    role: master
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
    role: master

